#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

rm -rf 0
cp -r org0 0
cp system/controlDict0 system/controlDict
cp system/fvSolution0 system/fvSolution
mkdir -p constant/triSurface

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#scale stl file
surfaceTransformPoints -scale "(1e-3 1e-3 1e-3)" dogbone.stl constant/triSurface/dogbone.stl

runApplication blockMesh
#runApplication surfaceFeatures
#surfaceFeatureExtract -includedAngle "150" -minElem "0" -minLen "0" constant/triSurface/inlet.stl constant/triSurface/inlet.eMesh


runApplication snappyHexMesh -overwrite
runApplication createPatch -overwrite

#run in parallel
#decomposePar -copyZero
#runParallel     snappyHexMesh -overwrite
# runApplication reconstructParMesh -constant -noZero
# runApplication splitMeshRegions -cellZones -defaultRegionName sol -overwrite
# # runApplication transformPoints -scale "(1e-3 1e-3 1e-3)"
